<template>
   <v-card flat class="pt-4 grey lighten-3" min-height="400">
      <div class="text-center blue--text text--darken-4 font-weight-bold">
         Loading...
      </div>
      <div class="mx-auto">
         <svg
               xmlns="http://www.w3.org/2000/svg"
               xmlns:xlink="http://www.w3.org/1999/xlink"
               style="
               margin:auto
               background: rgb(255, 255, 255);
               display: block;
               shape-rendering: auto;
               animation-play-state: running;
               animation-delay: 0s;
               "
               width="250px"
               height="250px"
               viewBox="0 0 100 100"
               preserveAspectRatio="xMidYMid"
         >
               <circle
               cx="50"
               cy="50"
               r="19"
               stroke-width="5"
               stroke="#002147"
               stroke-dasharray="29.845130209103033 29.845130209103033"
               fill="none"
               stroke-linecap="round"
               style="animation-play-state: running; animation-delay: 0s"
               >
               <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
               ></animateTransform>
               </circle>
               <circle
               cx="50"
               cy="50"
               r="13"
               stroke-width="5"
               stroke="#4270a9"
               stroke-dasharray="20.420352248333657 20.420352248333657"
               stroke-dashoffset="20.420352248333657"
               fill="none"
               stroke-linecap="round"
               style="animation-play-state: running; animation-delay: 0s"
               >
               <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;-360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
               ></animateTransform>
               </circle>
               <!-- [ldio] generated by https://loading.io/ -->
         </svg>
      </div>
   </v-card>
</template>

<script>
export default {

}
</script>

<style>

</style>